@startuml
class GetBookActivity {
    + execute(GetBookRequest) : GetBookResponse
}

class RemoveBookFromCatalogActivity {
    + execute(RemoveBookFromCatalogRequest) : RemoveBookFromCatalogResponse
}

class SubmitBookForPublishingActivity {
    + execute(SubmitBookForPublishingRequest) : SubmitBookForPublishingResponse
}

class CatalogItemVersion {
    - @DynamoDBHashKey bookId : String
    - @DynamoDBRangeKey version : int
    - inactive : boolean
    - author : String
    - text : String
    - genre : BookGenre
}

class RecommendationsServiceClient {
}

class PublishingStatusItem {
    - @DynamoDBHashKey publishingRecordId : String
    - @DynamoDBRangeKey status : PublishingRecordStatus
    - statusMessage : String
    - bookId : String

}

class CatalogDao {
    - dynamoDbMapper : DynamoDBMapper

    + CatalogDao(DynamoDBMapper)
}

class PublishingStatusDao {
    - dynamoDbMapper : DynamoDBMapper

    + PublishingStatusDao(DynamoDBMapper)
}

class BookNotFoundException {
}

GetBookActivity --> CatalogDao
GetBookActivity --> RecommendationsServiceClient
SubmitBookForPublishingActivity --> PublishingStatusDao
CatalogItemVersion --> CatalogDao
PublishingStatusItem --> PublishingStatusDao
CatalogDao --> BookNotFoundException
@enduml