@startuml
title RemoveBookFromCatalog

actor Client

participant execute
participant removeBookFromCatalog
participant BookNotFoundException
participant RemoveBookFromCatalogResponse
participant RemoveBookFromCatalogActivity
participant CatalogDao
@enduml
